// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use alloy_primitives::{address, Address};
use common::{GuardianSet, GuestInput, VAA};
use methods::METHOD_ELF;
use risc0_ethereum_contracts::encode_seal;
use risc0_zkvm::{default_prover, ExecutorEnv, ProverOpts, VerifierContext};

const TEST_GUARDIAN_PUB: Address = address!("0xbeFA429d57cD18b7F8A4d91A2da9AB4AF05d0FBe");

fn main() {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    if std::env::var("BONSAI_API_KEY").is_err() {
        eprintln!("Error: BONSAI_API_KEY environment variable is not set. You most likely want to be using Bonsai for proving so set BONSAI_API_KEY and BONSAI_API_URL env vars");
        std::process::exit(1);
    }

    let vaa_bytes = hex::decode(
        std::env::args()
            .nth(1)
            .expect("Expects a single hex encoded VAA as argument"),
    )
    .expect("Hex decode failed");

    // in reality this would read the guardian set pubkeys from the contract
    let guardian_set = GuardianSet {
        index: 0,
        keys: vec![TEST_GUARDIAN_PUB],
        creation_time: 0,
        expiration_time: 0,
    };

    let input = GuestInput {
        vaa_bytes: vaa_bytes.clone(),
        guardian_set,
    };

    let env = ExecutorEnv::builder()
        .write_frame(&input.encode().unwrap())
        .build()
        .unwrap();

    println!("Starting proving of the program");
    let receipt = default_prover()
        .prove_with_ctx(
            env,
            &VerifierContext::default(),
            METHOD_ELF,
            &ProverOpts::groth16(),
        )
        .unwrap()
        .receipt;

    println!("proving complete, encoding VAA");

    // Encode the seal with the selector.
    let seal = encode_seal(&receipt).unwrap();

    let mut vaa = VAA::deserialize(&vaa_bytes).unwrap();
    vaa.version = 2;
    vaa.signatures = vec![];
    vaa.seal = seal;

    println!("VAA: {:?}", hex::encode(vaa.serialize()));
}
