[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { version = "2.0" }
risc0-build-ethereum = { git = "https://github.com/risc0/risc0-ethereum", rev = "v2.0.0-rc.3" }

[dependencies]
alloy-sol-types = "0.8.24"

[dev-dependencies]
alloy-primitives = "0.8.24"
hex-literal = "1.0.0"
risc0-zkvm = { version = "2.0", features = ["client", "unstable"] }
common = { path = "../common" }
risc0-ethereum-contracts = { git = "https://github.com/risc0/risc0-ethereum", rev = "v2.0.0-rc.3" }
hex = "0.4.3"


[package.metadata.risc0]
methods = ["guest"]
